# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string
      source-sha:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
# Please do not rename this job
  build-project:
    name: build cmi-website
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source-sha }}
          submodules: 'recursive'

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 7c7fa450-8959-44b2-9961-6a3820c74469
          branch-id: ${{ inputs.branch-id }}
          version: ${{ inputs.source-sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/cmi-website/config.yaml
          action: upload
